### ISSUE TITLE
Use Github Actions instead of Travis?

### ISSUE THREAD

**Issue by k00ni** [raphaelstolt/php-jsonpointer#14]
Helpful library! Would you be open to transition to Github Actions and abandon Travis?

Travis not only got unreliable for Open Source projects (experienced it myself: tests weren't triggered after commits, not running for days), but may not be free anymore for them also.

Sources:
* https://www.nymedia.no/en/blog/why-we-decided-migrate-from-travis-to-github-action
* https://www.codetd.com/en/article/12116056

If you agree I can make a pull request and we can discuss details.

**Comment by raphaelstolt** [comment]
Yes I would be open for a transition to GitHub Actions.
